In [1]:
import pandas as pd
import numpy as np

DATA_RAW = '../data/household_power_consumption_eda.csv'
df = pd.read_csv(DATA_RAW, sep=',', low_memory=False)

pd.set_option('display.precision', 2)

### Remove corrupt rows

In [2]:
df.dropna(subset=['Sub_metering_3'], inplace=True)

In [3]:
df[df['Sub_metering_3'].isnull()].head()

Empty DataFrame
Columns: [Date, Time, Global_active_power, Global_reactive_power, Voltage, Global_intensity, Sub_metering_1, Sub_metering_2, Sub_metering_3]
Index: []

### Merging the date and time columns

In [4]:
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], dayfirst=True)
df.drop(columns=['Date', 'Time'], inplace=True)

In [5]:
df.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime
0,4.22,0.42,234.84,18.4,0.0,1.0,17.0,2006-12-16 17:24:00
1,5.36,0.44,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,5.37,0.50,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,5.39,0.50,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
4,3.67,0.53,235.68,15.8,0.0,1.0,17.0,2006-12-16 17:28:00

### Decomposing the datetime column

In [6]:
df['Year'] = df['Datetime'].dt.year
df['Month'] = df['Datetime'].dt.month
df['Day'] = df['Datetime'].dt.day
df['Hour'] = df['Datetime'].dt.hour
df['Minute'] = df['Datetime'].dt.minute    

df.drop(columns=['Datetime'], inplace=True)

In [7]:
df.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Year,Month,Day,Hour,Minute
0,4.22,0.42,234.84,18.4,0.0,1.0,17.0,2006,12,16,17,24
1,5.36,0.44,233.63,23.0,0.0,1.0,16.0,2006,12,16,17,25
2,5.37,0.50,233.29,23.0,0.0,2.0,17.0,2006,12,16,17,26
3,5.39,0.50,233.74,23.0,0.0,1.0,17.0,2006,12,16,17,27
4,3.67,0.53,235.68,15.8,0.0,1.0,17.0,2006,12,16,17,28

In [8]:
df.to_csv('../data/household_power_consumption_preprocess_01.csv', index=False)

Benchmark training results:

RMSE: 0.0305
R2 percentage: 99.91757647499917
Mean absolute percentage error: 0.020562466632309068

### dropping the Global_intensity column

Since it is noticed that the Global_intensity column has a '1' correlation with the target column, It is decided to drop the column

In [9]:
df.drop(columns=['Global_intensity'], inplace=True)

In [10]:
df.to_csv('../data/household_power_consumption_preprocess_02.csv', index=False)

Second training results:

RMSE: 0.3292
R2 percentage: 90.39148692587199
Mean absolute percentage error: 0.21050393389317576